apiVersion: v1
kind: Service
metadata:
  name: ping-monitor
  namespace: default
spec:
  selector:
    app: ping-monitor
  ports:
    - name: https
      port: 443
      targetPort: 8089
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 184.60.25.132/32
