apiVersion: v1
kind: Service
metadata:
  name: ping-monitor
  namespace: default
spec:
  selector:
    app: ping-monitor
  ports:
    - name: https
      port: 8089
      targetPort: 8089
      nodePort: 8089
  type: NodePort
